version: "3.7"
volumes:
  postgres-db: ~
services:
  arent-health-app:
    build: ../arent-health-app
    ports:
      - 8086:8086
  postgres-db:
    restart: always
    image: postgres
    hostname: postgres-db
    container_name: db-postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=123456aA@"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
    volumes:
      - postgres-db:/var/lib/postgresql/data\